platform:ios, '9.0'

use_frameworks!

target 'XJHNetworkReachability_Example' do
  pod 'XJHNetworkReachability', :path => '../'
  
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'MLeaksFinder', '~> 1.0.0'

  target 'XJHNetworkReachability_Tests' do
    inherit! :search_paths

    
  end
end
